### ISSUE TITLE
Does ObscuredSharedPreferences.getPrefs only support one file per app?

### ISSUE THREAD

**Issue by webmaster128** [RightHandedMonkey/WorxForUs_Library#2]
Given this constructor

```
    public synchronized static ObscuredSharedPreferences getPrefs(Context c, String appName, int contextMode) {
        if (prefs == null) {
            //make sure to use application context since preferences live outside an Activity
            //use for objects that have global scope like: prefs or starting services
            prefs = new ObscuredSharedPreferences(
                    c.getApplicationContext(), c.getApplicationContext().getSharedPreferences(appName, contextMode) );
        }
        return prefs;
    }
```

Am I right that `ObscuredSharedPreferences` only supports one set of settings (i.e. one file in `/data/data/my.app/shared_prefs/`)?

Because when I call that with different values for `appName`, only the first one sets the `prefs` variable.

**Comment by RightHandedMonkey** [comment]
Right, the call to getPrefs references a static variable which is set the first time you call it.  It is basically cashed by the class so any call will return that same 'prefs' instance.  In order to do what you are asking, you need to reset prefs to null before calling getPrefs(...) to work on the second set of settings.  You would need to add something like the code below to do that:

  public void static ObscuredSharedPreferences disconnectPrefs() {
    prefs = null;
  }
  
Call with this, in order to recreate a connection to another file:
  ObscuredSharedPreferences.disconnectPrefs();
  //Now make a new call to getPrefs(...)

**Comment by webmaster128** [comment]
Thanks for your feedback and confirmation. I think it is more intuitive to a user who worked with SharedPrefs to support multiple pref files. This did already cause hard to debug trouble in our company, because prefs have been stored kind of randomly. The PR adds support for that with minimal change. Users who use ObscuredSharedPreferences.getPrefs with just the app name, should be able to do that without any change in behaviour.

**Comment by RightHandedMonkey** [comment]
Sure, I'll take care of that.  You're absolutely right on this one.  Just one question, what is the PR?

**Comment by webmaster128** [comment]
The pull request #3 allows using multiple pref files and thus fixes this issue.

**Comment by webmaster128** [comment]
Done in https://github.com/RightHandedMonkey/WorxForUs_Library/commit/b07cbebe76ca00c72b5466f384b7bbeaa0cdf0eb
